name: 04- Using Actions

on: push

jobs:
    Build:
        runs-on: ubuntu-latest
        defaults:
            run: 
                working-directory: 02-using-actions/react-app
                
        steps:
            - name: Checkout file
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                    node-version: '20.x'
            - name: Install Dependecies
              run: npm install
            - name: Run unit test
              run: npm run test
            - name: Printing folders
              run: ls

