name: 08 - Environment Variables

on:
    push:
    workflow_dispatch:

jobs:
    echo:
        runs-on: ubuntu-latest
        env:
            first_name: "Pankaj Naval"
        steps: 
            - name: Print Environment Variables
              run: |
                echo "Name $first_name"
